name: Publish to PyPI

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.4"

      - name: Build and publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_API_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python3 -m pip install build twine
          python3 -m build
          python3 -m twine upload dist/*
